config/routes.rb
Hikist::Application.routes.draw do
  resources :users do
    member do
      get :following, :leading
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :hikelogs, only: [:create, :destroy, :show, :new, :edit, :update]
  resources :relationships, only: [:create, :destroy]

  root to: 'static_pages#home'
  
  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/help', to: 'static_pages#help'
  match '/about', to: 'static_pages#about'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def home
  	if signed_in?
  	  @hikelog    = current_user.hikelogs.build
  	  @feed_items = current_user.feed.paginate(page: params[:page])
  	end
  end

  def help
  end

  def about
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About Us</h1>
<p>About the Hikist.com team!</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>Help page for hikist.com</p>

app/views/static_pages/home.html.erb
<% if signed_in? %>
  <div class="row">
  	<aside class="span4">
  	  <section>
  	  	<%= render 'shared/user_info' %>
  	  </section>
      <section>
        <%= render 'shared/followstats' %>
      </section>
  	  <section>
  	  	<%= link_to "Create New Hikelog!", new_hikelog_path,
                      class: "btn btn-large btn-primary" %>
  	  </section>
  	</aside>
    <div class="span7">
      <h3>Hikes</h3>
      <%= render 'shared/feed' %>
    </div>
  </div>
<% else %>
<div class="center hero-unit">
  <h1>Welcome to Hikist</h1>
  <p>Hikist is your place to archive, share and discover hikes.</p>
  <%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>
</div>
<% end %>