config/routes.rb
Hikist::Application.routes.draw do
  resources :users do
    member do
      get :following, :leading
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :hikelogs, only: [:create, :destroy, :show, :new, :edit, :update]
  resources :relationships, only: [:create, :destroy]

  root to: 'static_pages#home'
  
  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/help', to: 'static_pages#help'
  match '/about', to: 'static_pages#about'

end

app/views/shared/_best.html.erb
<!-- Stub start for personal best widget thing not currently displayed anywhere -->

Personal Best: <%= @hikelog.user.hikelogs.maximum("length_of_hike") %> miles
<%= image_tag("blue.jpg", size: "15x1") %>
<img src="/assets/blue.jpg" height="1" width="100">
<div size="100x5" border="1">
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
  	<div class="alert alert-error">
  	  The form contains <%= pluralize(object.errors.count, "error") %>.
  	</div>
  	<ul>
  	  <% object.errors.full_messages.each do |msg| %>
  	    <li>* <%= msg %></li>
  	  <% end %>
  	</ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items %>
  <ol class="hikelogs">
  	<%= render partial: 'shared/feed_item', collection: @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
  <%= link_to gravatar_for(feed_item.user), feed_item.user %>
  <span class="user">
  	<%= link_to feed_item.user.name, feed_item.user %>
  </span>
  <span class="title">
    <%= link_to feed_item.title, feed_item %></span>
  <span class="date">
  	<%= feed_item.date_of_hike.to_formatted_s(:long_ordinal) %>
  </span>
  <span class="length">
  	<%= feed_item.length_of_hike %> Miles
  </span>
</li>

app/views/shared/_followstats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    Trailing
    <strong id="following" class="stat">
      <%= @user.leaders.count %>
    </strong>
    <%= pluralize_without_count(@user.leaders.count, "Hikist") %>
  </a>
  <a href="<%= leading_user_path(@user) %>">
    Leading
    <strong id="leading" class="stat">
      <%= @user.followers.count %>
    </strong>
    <%= pluralize_without_count(@user.followers.count, "Hikist") %>
  </a>
</div>

app/views/shared/_hikelog_form.html.erb
<%= form_for(@hikelog) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="hikelog_label">
    Title
  </div>
  <div class="field"> 
  	<%= f.text_field :title, placeholder: "100 characters maximum" %>
  </div>
  <div class="hikelog_label">
    Hikelog report
  </div>
  <div class="field">
  	<%= f.text_area :content, placeholder: "1,000 words maximum", rows: 10 %>
  </div>
  <div class="hikelog_label">
    Location - optional
  </div>
  <div class="field">
  	<%= f.text_field :location, placeholder: "Place, state" %>
  </div>
  <div class="hikelog_label">
    Date of hike - yyyy-mm-dd
  </div>
  <div class="field">
  	<%= f.text_field :date_of_hike, placeholder: "yyyy-mm-dd" %>
  </div>
  <div class="hikelog_label">
    Length of hike in miles - optional
  </div>
  <div class="field">
  	<%= f.text_field :length_of_hike, placeholder: "Miles" %>
  </div>
  <div class="hikelog_label">
    Total Elevation change during hike - optional
  </div>
  <div class="field">
  	<%= f.text_field :elevation_change, placeholder: "Feet" %>
  </div>
  <%= f.submit "Post", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_stats.html.erb
  <h3> Hiker Stats </h3>
    Total Hikist Miles: <%= @user.hikelogs.sum("length_of_hike") %> <br>
    Total Elevation Change: <%= @user.hikelogs.sum("elevation_change") %><br>
    Personal Best Distance: <%= @user.hikelogs.maximum("length_of_hike") %> miles

app/views/shared/_user_info.html.erb
<a href="<%= user_path(current_user) %>">
  <%= gravatar_for current_user, size: 52 %>
</a>
<h1>
  <%= current_user.name %>
</h1>
<span>
  <%= link_to "view my profile", current_user %>
</span>
<span>
  <%= pluralize(current_user.hikelogs.count, "Hike") %>
</span>