config/routes.rb
Hikist::Application.routes.draw do
  resources :users do
    member do
      get :following, :leading
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :hikelogs, only: [:create, :destroy, :show, :new, :edit, :update]
  resources :relationships, only: [:create, :destroy]

  root to: 'static_pages#home'
  
  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/help', to: 'static_pages#help'
  match '/about', to: 'static_pages#about'

end

app/models/hikelog.rb
# == Schema Information
#
# Table name: hikelogs
#
#  id               :integer          not null, primary key
#  content          :text
#  user_id          :integer
#  title            :string(255)
#  location         :string(255)
#  date_of_hike     :date
#  length_of_hike   :decimal(, )
#  elevation_change :integer
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#

class Hikelog < ActiveRecord::Base
  attr_accessible :content, :date_of_hike, :elevation_change,
  				  :length_of_hike, :location, :title
  belongs_to :user
  validates :content, :user_id, :title, :date_of_hike, presence: true
  validates :content, length: { maximum: 1000,
  			tokenizer: lambda { |str| str.scan(/\w+/) },
  			too_long: "must have at most %{count} words"
  }
  validates :title, :location, length: { maximum: 100 }
  validates :length_of_hike, :elevation_change, numericality: true
  default_scope order: 'hikelogs.date_of_hike DESC'

  def self.from_users_followed_by(user)
    leader_ids = "SELECT leader_id FROM relationships
                 WHERE follower_id = :user_id"
    where("user_id IN (#{leader_ids}) OR user_id = :user_id",
          user_id: user)
  end
end

app/controllers/hikelogs_controller.rb
class HikelogsController < ApplicationController
  before_filter :signed_in_user, only: [:create, :destroy, :new, :edit, :update]
  before_filter :correct_user,   only: [:destroy, :edit, :update]

  def new
    @hikelog = current_user.hikelogs.new
  end

  def edit
  end

  def update
    if @hikelog.update_attributes(params[:hikelog])
      flash[:success] = "Hikelog updated"
      redirect_to @hikelog
    else
      render 'edit'
    end
  end

  def show
    @hikelog = Hikelog.find_by_id(params[:id])
  end

  def create
  	@hikelog = current_user.hikelogs.build(params[:hikelog])
  	if @hikelog.save
  	  flash[:success] = "Hike added!"
  	  redirect_to root_url
  	else
      @feed_itmes = []
      render 'hikelogs/new'
  	  #render 'static_pages/home'
  	end
  end

  def destroy
    @hikelog.destroy
    redirect_to root_url
  end

  private

    def correct_user
      @hikelog = current_user.hikelogs.find_by_id(params[:id])
      redirect_to root_url if @hikelog.nil?
    end
    
end

app/views/hikelogs/_hikelog.html.erb
<li>
  <span class="title"><%= link_to hikelog.title, hikelog %></span>
  <span class="date">
  	Hiked <%= hikelog.date_of_hike.to_formatted_s(:long_ordinal) %>
  </span>
  <% if current_user?(hikelog.user) %>
    <%= link_to "delete", hikelog, method: :delete,
    							   data: { confirm: "Are you sure?" }, 
    							   title: hikelog.title %>
  <% end %>
</li>

app/views/hikelogs/edit.html.erb
<% provide(:title, 'Edit hikelog') %>
<h1>Update your hikelog</h1>
<div class="row">
  <div class="span6 offset3">
  <section>
<%= form_for(@hikelog) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  
  	<%= f.label :title %>
  	<%= f.text_field :title, placeholder: "100 characters maximum" %>

  	<%= f.label :content, "Hikelog report" %>
  	<%= f.text_area :content, placeholder: "1,000 words maximum", rows: 10 %>
  
  	<%= f.label :location, "Location - optional" %>
  	<%= f.text_field :location, placeholder: "Place, state" %>

  	<%= f.label :date_of_hike, "Date of hike - yyyy-mm-dd" %>
  	<%= f.text_field :date_of_hike, placeholder: "yyyy-mm-dd" %>

  	<%= f.label :length_of_hike, "Length of hike in miles - optional" %>
  	<%= f.text_field :length_of_hike, placeholder: "Miles" %>
  
  	<%= f.label :elevation_change, "Total Elevation change during hike - optional" %>
  	<%= f.text_field :elevation_change, placeholder: "Feet" %>

  <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
<% end %>

  </section>
  </div>
</div>

app/views/hikelogs/new.html.erb
<% provide(:title, 'Add hikelog') %>
<h1>Add hikelog</h1>
<div class="row">
  <div class="span6 offset3">
  <section>
  	<%= render 'shared/hikelog_form' %>
  </section>
  </div>
</div>

app/views/hikelogs/show.html.erb
<% provide(:title, @hikelog.title) %>
<div class="row">
  <div class="span6 offset3">
  	  <h3><%= @hikelog.title %></h3>
      <p class="main_hikelog"><%= @hikelog.content %></p>
  	  <ol class="hikestats">
        <li>Location: <%= @hikelog.location %></li>
        <li>Date: <%= @hikelog.date_of_hike.to_formatted_s(:long_ordinal) %></li>
        <li>Distance: <%= @hikelog.length_of_hike %> Miles</li>
        <li>Elevation: <%= @hikelog.elevation_change %> Feet</li>
  	  </ol>
      <% if current_user?(@hikelog.user) %>
      <div class="edit_buttons">
      <%= link_to "Delete", @hikelog, method: :delete,
                                     data: { confirm: "Are you sure?" },
                                     title: @hikelog.title,
                                     class: "btn btn-large btn-primary" %>
      </div>
      <div class="edit_buttons">
      <%= link_to "Update hikelog", edit_hikelog_path,
                                     class: "btn btn-large btn-primary" %>
      </div>
      <% end %>
  </div>
</div>